<?php

namespace App\Database\Seeders;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'category_id' => 1,
                'name' => 'Red Rose Bouquet',
                'slug' => 'red-rose-bouquet',
                'description' => 'A beautiful bouquet of fresh red roses, perfect for expressing love and romance.',
                'short_description' => '12 premium red roses with greenery',
                'sku' => 'RB-001',
                'price' => 49.99,
                'sale_price' => 44.99,
                'cost_price' => 25.00,
                'stock_quantity' => 50,
                'min_stock_level' => 10,
                'weight' => 1.5,
                'dimensions_length' => 30.0,
                'dimensions_width' => 25.0,
                'dimensions_height' => 40.0,
                'images' => json_encode(['red-rose-bouquet-1.jpg', 'red-rose-bouquet-2.jpg']),
                'tags' => json_encode(['romantic', 'valentine', 'love', 'red']),
                'meta_title' => 'Red Rose Bouquet - Fresh Flowers',
                'meta_description' => 'Order beautiful red rose bouquets online. Fresh flowers delivered to your door.',
                'status' => 'active',
                'is_featured' => true,
                'is_digital' => false,
                'track_stock' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 1,
                'name' => 'White Rose Arrangement',
                'slug' => 'white-rose-arrangement',
                'description' => 'Elegant white roses arranged in a beautiful vase, perfect for weddings and special occasions.',
                'short_description' => '15 white roses in a glass vase',
                'sku' => 'WR-002',
                'price' => 59.99,
                'cost_price' => 30.00,
                'stock_quantity' => 30,
                'min_stock_level' => 8,
                'weight' => 2.0,
                'dimensions_length' => 35.0,
                'dimensions_width' => 30.0,
                'dimensions_height' => 45.0,
                'images' => json_encode(['white-rose-arrangement-1.jpg']),
                'tags' => json_encode(['elegant', 'wedding', 'white', 'pure']),
                'meta_title' => 'White Rose Arrangement - Elegant Flowers',
                'meta_description' => 'Elegant white rose arrangements perfect for weddings and special events.',
                'status' => 'active',
                'is_featured' => false,
                'is_digital' => false,
                'track_stock' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 2,
                'name' => 'Pink Lily Bouquet',
                'slug' => 'pink-lily-bouquet',
                'description' => 'Delicate pink lilies that bring beauty and fragrance to any room.',
                'short_description' => '10 pink lilies with filler flowers',
                'sku' => 'PL-003',
                'price' => 39.99,
                'cost_price' => 20.00,
                'stock_quantity' => 40,
                'min_stock_level' => 10,
                'weight' => 1.2,
                'dimensions_length' => 28.0,
                'dimensions_width' => 22.0,
                'dimensions_height' => 38.0,
                'images' => json_encode(['pink-lily-bouquet-1.jpg']),
                'tags' => json_encode(['pink', 'fragrant', 'delicate', 'spring']),
                'meta_title' => 'Pink Lily Bouquet - Fragrant Flowers',
                'meta_description' => 'Beautiful pink lilies with wonderful fragrance. Perfect for any occasion.',
                'status' => 'active',
                'is_featured' => false,
                'is_digital' => false,
                'track_stock' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 3,
                'name' => 'Colorful Tulip Mix',
                'slug' => 'colorful-tulip-mix',
                'description' => 'A vibrant mix of colorful tulips that brighten any day.',
                'short_description' => '20 mixed color tulips',
                'sku' => 'TM-004',
                'price' => 34.99,
                'cost_price' => 18.00,
                'stock_quantity' => 60,
                'min_stock_level' => 15,
                'weight' => 1.0,
                'dimensions_length' => 25.0,
                'dimensions_width' => 20.0,
                'dimensions_height' => 35.0,
                'images' => json_encode(['tulip-mix-1.jpg', 'tulip-mix-2.jpg']),
                'tags' => json_encode(['colorful', 'spring', 'mixed', 'vibrant']),
                'meta_title' => 'Colorful Tulip Mix - Spring Flowers',
                'meta_description' => 'Vibrant mix of colorful tulips perfect for spring and special occasions.',
                'status' => 'active',
                'is_featured' => true,
                'is_digital' => false,
                'track_stock' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 4,
                'name' => 'White Orchid Plant',
                'slug' => 'white-orchid-plant',
                'description' => 'Elegant white orchid plant that lasts for months with proper care.',
                'short_description' => 'White phalaenopsis orchid in decorative pot',
                'sku' => 'OP-005',
                'price' => 79.99,
                'cost_price' => 45.00,
                'stock_quantity' => 20,
                'min_stock_level' => 5,
                'weight' => 3.0,
                'dimensions_length' => 40.0,
                'dimensions_width' => 35.0,
                'dimensions_height' => 50.0,
                'images' => json_encode(['orchid-plant-1.jpg']),
                'tags' => json_encode(['exotic', 'long-lasting', 'elegant', 'plant']),
                'meta_title' => 'White Orchid Plant - Exotic Flowers',
                'meta_description' => 'Beautiful white orchid plants that last for months. Perfect gift for any occasion.',
                'status' => 'active',
                'is_featured' => false,
                'is_digital' => false,
                'track_stock' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('products')->insertBatch($products);
    }
}
